window.MOVENSO_PACKS = [
  {
    id: "judo-kodokan",
    title: "Judo",
    discipline: "Judo",
    summary: "Une base structurée du judo suivant la nomenclature Kodokan, avec une navigation relationnelle bêta — chaque lien (préparations, enchaînements, contres, katas, fondamentaux) est expliqué par une courte raison — et des liens de démonstration lorsqu'ils existent.",
    type: "beta",
    statusLabel: "Bêta",
    version: "0.3.0",
    updatedAt: "26 juillet 2026",
    itemCount: "111 techniques · 825 liens expliqués",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Nomenclature", "Relations expliquées", "Liens vidéo"],
    href: "packs/judo.movpack",
    downloadName: "judo.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  },
  {
    id: "karate-shotokan",
    title: "Karaté Shotokan",
    discipline: "Karaté",
    summary: "Point de départ pour structurer une bibliothèque de karaté Shotokan, à compléter et adapter après import.",
    type: "alpha",
    statusLabel: "Alpha",
    version: "0.1.0",
    updatedAt: "25 juillet 2026",
    itemCount: "109 techniques",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Techniques", "Personnalisable"],
    href: "packs/karate-shotokan.movpack",
    downloadName: "karate-shotokan.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  },
  {
    id: "jujitsu-france-judo",
    title: "Jujitsu",
    discipline: "Jujitsu",
    summary: "Une base de jujitsu (nomenclature France Judo) pour démarrer et adapter à sa propre pratique.",
    type: "alpha",
    statusLabel: "Alpha",
    version: "0.1.0",
    updatedAt: "25 juillet 2026",
    itemCount: "162 techniques",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Techniques", "Personnalisable"],
    href: "packs/jujitsu.movpack",
    downloadName: "jujitsu.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  },
  {
    id: "jjb-gi-nogi",
    title: "Jiu-jitsu brésilien",
    discipline: "JJB",
    summary: "Une base de JJB couvrant Gi et No-Gi, comme point de départ personnalisable.",
    type: "alpha",
    statusLabel: "Alpha",
    version: "0.1.0",
    updatedAt: "25 juillet 2026",
    itemCount: "150 techniques",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Techniques", "Gi & No-Gi"],
    href: "packs/jjb.movpack",
    downloadName: "jjb.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  },
  {
    id: "taiso",
    title: "Taïso",
    discipline: "Taïso",
    summary: "Mouvements de taïso et 12 séances prêtes à dérouler avec le chronomètre intégré.",
    type: "alpha",
    statusLabel: "Alpha",
    version: "0.1.0",
    updatedAt: "25 juillet 2026",
    itemCount: "114 techniques · 12 séances",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Techniques", "12 séances", "Chrono"],
    href: "packs/taiso.movpack",
    downloadName: "taiso.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Les 12 séances sont incluses dans le pack. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  },
  {
    id: "yoga-hatha",
    title: "Yoga Hatha",
    discipline: "Yoga",
    summary: "Postures de Hatha yoga accessibles et 12 séances prêtes à suivre, incluses dans le pack.",
    type: "alpha",
    statusLabel: "Alpha",
    version: "0.1.0",
    updatedAt: "25 juillet 2026",
    itemCount: "72 postures · 12 séances",
    language: "Français",
    maintainer: "Movenso",
    license: "CC BY-NC-SA 4.0",
    features: ["Postures", "12 séances", "Chrono"],
    href: "packs/yoga.movpack",
    downloadName: "yoga.movpack",
    note: "Il s'agit d'un starter pack, pour ne pas démarrer à vide. Les 12 séances sont incluses dans le pack. Cette base de travail ne constitue pas une référence officielle : elle reste à vérifier et à enrichir selon vos besoins et votre apprentissage. Elle ne remplace pas l'enseignement d'un professeur."
  }
];
