(() => {
  "use strict";
  const config = window.MOVENSO_CONFIG || {};
  const menuButton = document.querySelector("[data-menu-button]");
  const nav = document.querySelector("[data-mobile-nav]");
  if (menuButton && nav) menuButton.addEventListener("click", () => {const open=menuButton.getAttribute("aria-expanded")==="true";menuButton.setAttribute("aria-expanded",String(!open));nav.hidden=open;});
  const setLink=(selector,url,fallback)=>document.querySelectorAll(selector).forEach(link=>{if(url){link.href=url;link.removeAttribute("aria-disabled");link.classList.remove("is-disabled");}else{link.removeAttribute("href");link.setAttribute("aria-disabled","true");link.classList.add("is-disabled");if(fallback) link.querySelector("[data-label]")?.replaceChildren(fallback);}});
  setLink("[data-link='play']",config.playStoreUrl,"Bientôt sur Google Play");setLink("[data-link='web']",config.webAppUrl);setLink("[data-link='releases']",config.releasesUrl);setLink("[data-link='repository']",config.repositoryUrl);setLink("[data-link='propose-pack']",config.packProposalUrl);setLink("[data-link='issue']",config.issueUrl);
  const list=document.querySelector("#pack-list"); if(!list) return;
  const packs=Array.isArray(window.MOVENSO_PACKS)?window.MOVENSO_PACKS:[]; const search=document.querySelector("#pack-search"); const discipline=document.querySelector("#pack-discipline"); const count=document.querySelector("#pack-count"); const empty=document.querySelector("#pack-empty");
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  [...new Set(packs.map(p=>p.discipline).filter(Boolean))].sort().forEach(name=>{const o=document.createElement("option");o.value=name;o.textContent=name;discipline?.append(o)});
  const render=()=>{const q=norm(search?.value.trim()); const selected=discipline?.value||""; const visible=packs.filter(p=>(!q||norm([p.title,p.discipline,p.summary,p.maintainer,...(p.features||[])].join(" ")).includes(q))&&(!selected||p.discipline===selected)); list.innerHTML=visible.map(p=>`<article class="pack-card"><div><p class="kicker">${esc(p.statusLabel)}</p><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><div class="pack-meta"><span>${esc(p.itemCount)}</span><span>v${esc(p.version)}</span><span>${esc(p.language)}</span></div><details><summary>Détails</summary><div class="pack-detail-panel"><p><strong>Maintenu par :</strong> ${esc(p.maintainer)} · <strong>Mise à jour :</strong> ${esc(p.updatedAt)} · <strong>Licence :</strong> ${esc(p.license)}</p><p>${esc(p.note)}</p></div></details></div><div class="pack-actions"><a class="button primary" href="${esc(p.href)}" download="${esc(p.downloadName)}">Télécharger</a></div></article>`).join(""); if(empty) empty.hidden=visible.length>0; if(count) count.textContent=visible.length===1?"1 pack disponible":`${visible.length} packs disponibles`;}; search?.addEventListener("input",render); discipline?.addEventListener("change",render); render();
})();